### ISSUE TITLE
Sparse memory based on memory pages

### ISSUE THREAD

**Issue by hgruniaux** [CPUlm/VirtualMachine#2]
Memory is actually implemented as a resizeable array. This naive method allows to not allocate all the memory until need but still allocates to much unused memory in most scenarions. A better approach should to use "memory pages": We split the memory into memmory pages (of the same size as the host OS memory pages).

This idea is the same that will be used in the Netlist simulator.

**Comment by hgruniaux** [comment]
We should reuse the code used in SimulatorC (it was coded with this in mind).

**Comment by desfreng** [comment]
Resolved in a7cf9b80144a87cbba4c1566b21dd7cc2ad65116.
